### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by mattcubero** [flowingsalt/BIM-Bot#8]
yo flowingsalt hit me up on discord i can give you my big ideas math account so you can fix the hack

disc: zerogzerogzerog

**Comment by blazebal** [comment]
did he add u?

**Comment by mattcubero** [comment]
nah not yet

**Comment by blazebal** [comment]
@flowingsalt fix this issue

**Comment by flowingsalt** [comment]
i already fixed it

**Comment by blazebal** [comment]
@flowingsalt it doesn’t work it keeps giving me an error

**Comment by blazebal** [comment]
i keep getting an error saying Unhandled Promise rejection: Unexpected identifier

**Comment by blazebal** [comment]
yo @flowingsalt did you manage to figure out the Cloudinary issue with the code? I’m still getting the 401 error.

**Comment by blazebal** [comment]
and if you did fix it with a new code please update it in the bookmark page
